### ISSUE TITLE
Support for restify 8

### ISSUE THREAD

**Issue by yagomassiah** [paulvarache/restify-paginate#18]
Well, restify 8 did get back the route.render, so restify-paginate works, kind of. It is now returning paginated responses but starting from the page 2 and not gettting the per_page or page parameters.

**Comment by paulvarache** [comment]
I have to admit I didn't maintain this module for a while. I heard the issues about restify 7 and 8 and will look into it in the next 24h.

Thank you so much for supporting this!

**Comment by paulvarache** [comment]
I just updated to restify 8 and can see all the tests passing. With a very simple demo I am able to get the correct page number. The page and per page parameters are only added if they are on the original request.

Can you describe more the issues you're having?

**Comment by yagomassiah** [comment]
So, I have an array of objects with 53 items. on my index.js I have 
``server.use(paginate(server));``

On the controller I pass the array to the getPaginatedResponse method

`` var ret1 = res.paginate.getPaginatedResponse(ret);``
  
``res.send(ret1);``

So I get an object like : 

``{
    "data": [
    ],
    "pages": {
        "last": "http://localhost:80//api/admin/pedidos?page=2",
        "next": "http://localhost:80//api/admin/pedidos?page=2"
    }
}``


First I don't get why I am getting the url with double "/" after the base url, second If I try to navigate to page=2 with the provided url (Removing one of the "/") it gets me the same results.

And third it is not reading the per_page or page parameters, my dataset contains 53 objects, even if I pass the parameters I can only see the first 50 and cannot limit them.  

It also misses the "last" and "first" properties. (well maybe cause I have two pages?)

**Comment by yagomassiah** [comment]
So @paulvarache any thoughts on why this is happening?

**Comment by samuelpecher** [comment]
@yagomassiah 

This (very useful) plugin is looking for the query params in `req.params` rather than `req.query`. You can work around this by passing `{mapParams: true}` into you call to the `queryParser()` plugin, which will force the `queryParser()` plugin to merge the parsed query params into `req.params`

```
const restify = require('restify');
const paginate = require('restify-paginate');
server.use(restify.plugins.queryParser({mapParams: true})) //note mapParams: true
server.use(paginate(server));
```

Looks like there's a problem in the [documentation for restify's `queryParser()` plugin](http://restify.com/docs/plugins-api/#queryparser):
- it states that by default it merges the query params into req.params -> this isn't the observed behaviour
- The first two bullet points for the options of that plugin also seem contradictory:

> options.mapParams: (Object) disable passing (optional, default true)
> options.mapParams: (Boolean) Copies parsed query parameters intoreq.params. (optional, default false)

**Comment by carlosfunk** [comment]
Using mapParams worked perfectly for me on restify 8, I've created PR #19  to update the readme.
